version: '3.7'



services:
  db:
    image: postgres:15
    container_name: fastcut_db
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s


  redis:
    image: redis:7
    container_name: fastcut_redis


  fastcut:
    build:
        context: .
    image: fastcut_image
    container_name: fastcut_app
    env_file:
      - .env-non-dev
    ports:
      - "3333:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    command: ["sh", "/Fastcut/docker/app.sh"]
